---
- include: preinstall.yml
  tags:
    - preinstall

- include: install.yml
  tags:
    - install


- include: clean.yml
  tags:
    - clean
- include: remove.yml
  tags:
    - remove
  when: remove is defined
